const $=s=>document.querySelector(s),TW='https://www.twse.com.tw',OA='https://openapi.twse.com.tw';
// T86 is intentionally NOT included: no automated/scored use until an explicit reusable licence or contract is registered.
const U={stock:`${TW}/rwd/zh/afterTrading/STOCK_DAY`,index:`${TW}/indicesReport/MI_5MINS_HIST`,snap:`${OA}/v1/exchangeReport/STOCK_DAY_ALL`,val:`${OA}/v1/exchangeReport/BWIBBU_ALL`,rev:`${OA}/v1/opendata/t187ap05_L`};
const okHost=u=>{const h=new URL(u).hostname;if(!['www.twse.com.tw','openapi.twse.com.tw'].includes(h))throw Error('非核准官方來源');return h},n=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:null},avg=a=>{a=a.filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null},fmt=x=>x==null?'—':Number(x).toLocaleString('zh-TW',{maximumFractionDigits:2});
function roc(s){const m=String(s||'').match(/(\d{2,3})\/(\d{2})\/(\d{2})/);return m?`${+m[1]+1911}-${m[2]}-${m[3]}`:null}
function old(iso){return iso?Math.floor((Date.now()-new Date(iso+'T00:00:00+08:00'))/864e5):999}
function months(c){const d=new Date(),a=[];for(let i=0;i<c;i++){const x=new Date(d.getFullYear(),d.getMonth()-i,1);a.push(`${x.getFullYear()}${String(x.getMonth()+1).padStart(2,'0')}01`)}return a}
async function jget(u){okHost(u);const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('官方資料連線失敗');return r.json()}
async function hist(code,c=6){const z=await Promise.all(months(c).map(async d=>{try{const j=await jget(`${U.stock}?date=${d}&stockNo=${code}&response=json`);if(j.stat!=='OK')return[];return j.data.map(x=>({d:x[0],iso:roc(x[0]),v:n(x[1]),o:n(x[3]),h:n(x[4]),l:n(x[5]),c:n(x[6])})).filter(x=>x.iso&&Number.isFinite(x.o)&&Number.isFinite(x.h)&&Number.isFinite(x.l)&&Number.isFinite(x.c)&&x.o>0&&x.h>0&&x.l>0&&x.c>0)}catch{return[]}})),m=new Map();z.flat().forEach(x=>m.set(x.iso,x));return[...m.values()].sort((a,b)=>a.iso.localeCompare(b.iso))}
async function ihist(c=6){const z=await Promise.all(months(c).map(async d=>{try{const j=await jget(`${U.index}?date=${d}&response=json`);if(j.stat!=='OK')return[];return j.data.map(x=>({d:x[0],iso:roc(x[0]),o:n(x[1]),h:n(x[2]),l:n(x[3]),c:n(x[4]),v:null})).filter(x=>x.iso&&x.c)}catch{return[]}})),m=new Map();z.flat().forEach(x=>m.set(x.iso,x));return[...m.values()].sort((a,b)=>a.iso.localeCompare(b.iso))}
function historyIntegrity(r,h){const need=h==='preopen'||h==='day'?60:h==='1m'?80:h==='3m'?120:220;if(!Array.isArray(r)||r.length<need)return{ok:false,reason:`有效日線不足：${r?.length||0}/${need}`,need,count:r?.length||0};const L=r.at(-1);if(!L?.iso||old(L.iso)>4)return{ok:false,reason:'最新交易日過舊',need,count:r.length};let maxGap=0;for(let i=1;i<r.length;i++){const a=new Date(r[i-1].iso+'T00:00:00+08:00'),b=new Date(r[i].iso+'T00:00:00+08:00'),g=Math.round((b-a)/864e5);if(Number.isFinite(g))maxGap=Math.max(maxGap,g)}if(maxGap>15)return{ok:false,reason:`歷史日線存在 ${maxGap} 天中斷，需確認停牌／資料缺漏`,need,count:r.length,maxGap};return{ok:true,reason:'歷史日線完整度通過',need,count:r.length,maxGap}}
const ma=(r,k)=>avg(r.slice(-k).map(x=>x.c));
function ema(v,p){if(v.length<p)return[];const k=2/(p+1),o=[];let q=avg(v.slice(0,p));for(let i=0;i<v.length;i++){if(i<p-1)o.push(null);else if(i===p-1)o.push(q);else{q=v[i]*k+q*(1-k);o.push(q)}}return o}
function macd(r){const c=r.map(x=>x.c),a=ema(c,12),b=ema(c,26),d=c.map((_,i)=>a[i]!=null&&b[i]!=null?a[i]-b[i]:null),e=ema(d.filter(x=>x!=null),9);let j=0;const s=d.map(x=>x==null?null:e[j++]),h=d.map((x,i)=>x!=null&&s[i]!=null?x-s[i]:null);return{dif:d.at(-1),sig:s.at(-1),hist:h.at(-1)}}
function rsi(r,p=14){if(r.length<=p)return null;let g=0,l=0;for(let i=r.length-p;i<r.length;i++){const d=r[i].c-r[i-1].c;d>0?g+=d:l-=d}return l===0?100:100-100/(1+(g/p)/(l/p))}
function kd(r,p=9){if(r.length<p+2)return{k:null,d:null};let K=50,D=50,pk=50,pd=50;for(let i=p-1;i<r.length;i++){const w=r.slice(i-p+1,i+1),lo=Math.min(...w.map(x=>x.l)),hi=Math.max(...w.map(x=>x.h)),v=hi===lo?50:(r[i].c-lo)/(hi-lo)*100;pk=K;pd=D;K=K*2/3+v/3;D=D*2/3+K/3}return{k:K,d:D,pk,pd}}
function candle(r){const a=r.at(-1),b=r.at(-2),body=Math.abs(a.c-a.o),rg=Math.max(.001,a.h-a.l),up=a.h-Math.max(a.o,a.c),lo=Math.min(a.o,a.c)-a.l;if(a.c>b.o&&a.o<b.c&&b.c<b.o)return'多方吞噬';if(a.c<b.o&&a.o>b.c&&b.c>b.o)return'空方吞噬';if(lo>body*2&&up<body)return'錘子線';if(up>body*2&&lo<body)return'長上影';if(body/rg<.12)return'十字線';if(a.c>a.o&&body/rg>.65)return'長紅K';if(a.c<a.o&&body/rg>.65)return'長黑K';return'一般K線'}
function tech(r,h){const hg=historyIntegrity(r,h);if(!hg.ok)throw Error(hg.reason);const L=r.at(-1),P=r.at(-2),m20=ma(r,20),m60=ma(r,60),m240=ma(r,240),v20=avg(r.slice(-20).map(x=>x.v)),vr=L.v&&v20?L.v/v20:null,look=h==='1m'?20:h==='3m'?60:Math.min(240,r.length),hi=Math.max(...r.slice(-look).map(x=>x.h)),lo=Math.min(...r.slice(-look).map(x=>x.l)),M=macd(r),R=rsi(r),K=kd(r),C=candle(r);let s=50,why=[];const ref=h==='day'?ma(r,5):h==='1m'?m20:h==='3m'?m60:(ma(r,120)||m60);L.c>ref?(s+=12,why.push('價格站上主要均線')):(s-=12,why.push('價格在主要均線下'));m20>m60?(s+=9,why.push('MA20高於MA60')):(s-=8,why.push('MA20低於MA60'));if(vr){if(L.c>P.c&&vr>1.2){s+=10;why.push('價漲量增')}else if(L.c<P.c&&vr>1.3){s-=10;why.push('價跌量增')}}const room=(hi/L.c-1)*100,risk=Math.abs((lo/L.c-1)*100);room>risk*1.4?s+=8:s-=5;if(M.dif!=null&&M.sig!=null)M.dif>M.sig&&M.hist>=0?s+=6:s-=6;if(R>=75)s-=4;else if(R>=50&&R<70)s+=4;if(K.k!=null){if(K.pk<=K.pd&&K.k>K.d&&K.k<80)s+=3;else if(K.pk>=K.pd&&K.k<K.d)s-=3}if(['多方吞噬','錘子線'].includes(C))s+=3;if(['空方吞噬','長上影','長黑K'].includes(C))s-=3;if(m240&&L.c>m240)s+=6;s=Math.max(0,Math.min(100,Math.round(s)));return{last:L,m20,m60,m240,vr,macd:M,rsi:R,kd:K,candle:C,support:lo,resist:hi,score:s,reasons:why,entryLow:null,entryHigh:null,historyIntegrity:hg}}
function market(r){const hg=historyIntegrity(r,'day');if(!hg.ok)throw Error(`大盤資料不完整：${hg.reason}`);const L=r.at(-1),m20=ma(r,20),m60=ma(r,60),M=macd(r),R=rsi(r);let s=50,w=[];L.c>m20?(s+=15,w.push('大盤站上20日線')):(s-=15,w.push('大盤跌破20日線'));L.c>m60?(s+=15,w.push('大盤站上60日線')):(s-=15,w.push('大盤跌破60日線'));M.dif>M.sig&&M.hist>=0?s+=10:s-=10;if(R>=50&&R<70)s+=5;else if(R>=75)s-=3;else if(R<35)s-=5;s=Math.max(0,Math.min(100,Math.round(s)));return{score:s,delta:s>=70?5:s<45?-8:0,state:s>=70?'🟢 偏多':s>=45?'🟡 震盪':'🔴 高風險',last:L,m20,m60,rsi:R,reasons:w,historyIntegrity:hg}}
async function extras(date){const [vals,revs]=await Promise.all([jget(U.val),jget(U.rev)]),V=new Map(),R=new Map(),I=new Map();vals.forEach(x=>V.set(String(x.Code),{code:String(x.Code),pe:n(x.PEratio),pb:n(x.PBratio),yield:n(x.DividendYield),date:x.Date,provenance:'observed'}));revs.forEach(x=>R.set(String(x['公司代號']),{code:String(x['公司代號']),period:x['資料年月'],mom:n(x['營業收入-上月比較增減(%)']),yoy:n(x['營業收入-去年同月增減(%)']),ytd:n(x['累計營業收入-前期比較增減(%)']),provenance:'observed'}));return{V,R,I,institutionStatus:{available:false,legal:false,reason:'TWSE T86 個股法人明細未登錄可重用授權，依法務 Source Gate 不抓取、不計分'}}}
function combine(a,h,m,v,i,r){a.technical=a.score;a.marketDelta=m.delta;a.score=Math.max(0,Math.min(100,a.score+m.delta));let d=0;const ratio=i&&Number.isFinite(i.total)&&a.last.v?i.total/a.last.v:null;if(ratio>=.02)d+=4;else if(ratio<=-.02)d-=4;if(r?.yoy!=null&&h!=='day'){const w=h==='3m'?5:h==='long'?4:3;if(r.yoy>=20)d+=w;else if(r.yoy<=-15)d-=w}a.score=Math.max(0,Math.min(100,a.score+d));a.factorDelta=d;a.val=v||null;a.inst=i||null;a.rev=r||null;a.instRatio=ratio;a.action=a.score>=75?'偏多｜等拉回可分批':a.score>=60?'觀察｜不追價':a.score>=45?'中性｜等待確認':'偏弱｜暫避';return a}
async function verify(code,r){const hg=historyIntegrity(r,'day');const s=await jget(U.snap),x=s.find(z=>String(z.Code)===String(code)),L=r.at(-1),c=x?n(x.ClosingPrice):null,match=!!(c&&Math.abs(c-L.c)<.001),fresh=old(L.iso)<=4;return{fresh,match,history:hg,complete:fresh&&match&&hg.ok,date:L.iso,text:x?`${fmt(L.c)} / ${fmt(c)}｜${hg.reason}`:'找不到代號'}}
function showMarket(m){$('#marketScore').textContent=m.score;$('#marketBody').innerHTML=`<div class=kpis><div class=kpi><b>${fmt(m.last.c)}</b><span>TAIEX</span></div><div class=kpi><b>${fmt(m.m20)}</b><span>MA20</span></div><div class=kpi><b>${fmt(m.m60)}</b><span>MA60</span></div><div class=kpi><b>${m.rsi?.toFixed(1)||'—'}</b><span>RSI</span></div></div><p><b>${m.state}</b>｜市場調整 ${m.delta>0?'+':''}${m.delta}</p>`}
function render(code,a,h,vf){if(!vf.complete){$('#result').innerHTML=`<h3 class=bad>⛔ 資料驗證未通過</h3><p>日期 ${vf.date||'—'}｜交叉比對 ${vf.text||'資料不足'}</p>`;return $('#result').classList.remove('hidden')}const v=a.val||{},i=a.inst||{},r=a.rev||{};$('#result').innerHTML=`<div class=toprow><div><div class=muted>${code}｜${h}</div><h2>${a.action}</h2><div class=mini>技術 ${a.technical}｜市場 ${a.marketDelta>0?'+':''}${a.marketDelta}｜官方基本/籌碼 ${a.factorDelta>0?'+':''}${a.factorDelta}</div></div><div class=bubble>${a.score}</div></div><div class=kpis><div class=kpi><b>${fmt(a.last.c)}</b><span>收盤</span></div><div class=kpi><b>${fmt(a.entryLow)}–${fmt(a.entryHigh)}</b><span>進場區</span></div><div class=kpi><b>${fmt(a.support)}</b><span>支撐</span></div><div class=kpi><b>${fmt(a.resist)}</b><span>壓力</span></div></div><h3>技術面</h3><div class=sourcegrid><div class=sourceitem><b>均線</b>MA20 ${fmt(a.m20)}｜MA60 ${fmt(a.m60)}｜MA240 ${fmt(a.m240)}</div><div class=sourceitem><b>成交量</b>${a.vr?a.vr.toFixed(2)+'x':'—'}</div><div class=sourceitem><b>MACD</b>DIF ${fmt(a.macd.dif)}｜Signal ${fmt(a.macd.sig)}</div><div class=sourceitem><b>RSI / KD</b>${a.rsi?.toFixed(1)||'—'}｜K ${a.kd.k?.toFixed(1)||'—'} D ${a.kd.d?.toFixed(1)||'—'}</div><div class=sourceitem><b>K線</b>${a.candle}</div><div class=sourceitem><b>驗證</b>✅ TWSE ${vf.date}</div></div><h3>官方基本面／籌碼</h3><div class=sourcegrid><div class=sourceitem><b>上市三大法人</b>${i.total!=null?`總計 ${fmt(i.total)} 股｜外資 ${fmt(i.foreign)}｜投信 ${fmt(i.trust)}`:'資料未取得／授權未確認，不計分'}</div><div class=sourceitem><b>估值</b>PE ${v.pe??'—'}｜PB ${v.pb??'—'}｜殖利率 ${v.yield!=null?v.yield+'%':'—'}</div><div class=sourceitem><b>最新月營收</b>${r.period?`${r.period}｜YoY ${r.yoy??'—'}%｜MoM ${r.mom??'—'}%｜累計 ${r.ytd??'—'}%`:'資料未取得／未通過驗證，不計分'}</div></div><h3>理由</h3><div class=reason>${a.reasons.map(x=>'• '+x).join('<br>')}</div>`;$('#result').classList.remove('hidden')}
