// Visible data/readiness status. OOS gates entry predictions/statistical claims; it never locks deterministic holding management.
(function(){
  const internalSummary=document.querySelector('#dataHealthSummary'),internalBody=document.querySelector('#marketDetailsBody'),publicSummary=document.querySelector('#readinessSummary'),publicBody=document.querySelector('#readinessBody');if(!internalSummary&&!publicSummary)return;
  const rt=window.STOCKLAB_RUNTIME||{},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`${url} ${r.status}`);return r.json()}
  function modelStatus(v,key){return v?.models?.[key]?.status||'UNKNOWN'}
  function coverage(m){const q=m?.coverage_metrics?.overall||{};return{dates:Number(q.distinct_trading_dates)||0,securities:Number(q.securities)||0,maxBars:Number(q.max_valid_bars_per_security)||0,entryReady:Number(q.securities_at_least_60_bars)||0,entryNeed:Number(m?.coverage_metrics?.entry_minimum_valid_bars)||60}}
  function entryReady(){return rt.productionPredictionReady===true&&rt.gates?.entryDecisionOosValidation===true&&rt.gates?.entryRangeExecutionValidation===true&&rt.gates?.entryConfidenceCalibration===true}
  function readyHtml(m,v){const c=coverage(m),entry=modelStatus(v,'entry_decision_9plus3'),scan=modelStatus(v,'entry_scanner_9plus3'),hold=modelStatus(v,'holding_rules'),free=v?.data_layer_progress?.twse_free_official_history||{},tpex=v?.data_layer_progress?.tpex_free_long_history||{};return `<div class=sourcegrid><div class=sourceitem><b>TWSE 免費官方歷史</b>${free.status==='TECHNICALLY_VALIDATED_NOT_PRODUCTION_ACTIVATED'?'技術驗證通過':'尚未驗證'}<br><span class=mini>${free.rows_per_ticker?`${free.rows_per_ticker} 日 × ${(free.tested_tickers||[]).join('／')}｜${free.first_date}～${free.last_date}`:'尚無通過結果'}；尚未 production activation。</span></div><div class=sourceitem><b>TPEx 免費長歷史</b>${tpex.status==='NOT_YET_CONFIRMED'?'尚未確認':'狀態待核對'}<br><span class=mini>目前免費官方 current／forward 與 context 可用，但完整長期個股 OHLCV 尚未驗證。</span></div><div class=sourceitem><b>合法歷史行情覆蓋</b>${c.dates} 個交易日｜${c.securities} 個標的<br><span class=mini>單一標的目前最多 ${c.maxBars} 根有效日線；這只影響需要歷史的衍生結構，不會被拿來補假資料。</span></div><div class=sourceitem><b>新部位入場模型</b>${esc(entry)}<br><span class=mini>OOS／可達性／校準未通過時不輸出可執行買價</span></div><div class=sourceitem><b>已持有管理</b>${esc(hold)}<br><span class=mini>使用成本、股數、買入日與最新合法已驗證收盤做規則式管理。OOS 只限制勝率／機率／校準信心，不作功能總開關。</span></div><div class=sourceitem><b>TOP10 入場模型</b>${esc(scan)}<br><span class=mini>必須與單股入場使用同一完整模型；不足 10 檔不補數</span></div></div><div class=mini style="margin-top:10px">缺少的歷史、風險狀態、公司行動、事件或市場背景維持未知，不以舊值、0、平均值、其他網站或 AI 補齊。持倉資料不足以形成價格型觸發線時顯示「—」，但不把整個持股分析鎖住。</div>`}
  function internalHtml(m,v){const c=coverage(m);return `<div class=source-note style="margin-top:0"><b>資料截止與模型 readiness</b><div class=sourcegrid style="margin-top:8px"><div class=sourceitem><b>最新合法官方資料</b>${esc(m?.last_date||'未取得')}</div><div class=sourceitem><b>合法歷史覆蓋</b>${c.dates} 個交易日｜單檔最多 ${c.maxBars} 根</div><div class=sourceitem><b>入場／TOP10</b>${esc(modelStatus(v,'entry_decision_9plus3'))}<br>${esc(modelStatus(v,'entry_scanner_9plus3'))}</div><div class=sourceitem><b>持股規則</b>${esc(modelStatus(v,'holding_rules'))}<br><span class=mini>規則式持股管理不依賴 OOS 解鎖</span></div></div></div>`}
  async function run(){if(internalSummary)internalSummary.textContent='正在核對合法資料日…';if(publicSummary)publicSummary.textContent='正在核對…';try{const [m,v]=await Promise.all([getJson('./history-ogdl/manifest.json'),getJson('./model-validation-status.json')]);if(m.schema_version!==1||m.source_class!=='ogdl_daily_archive'||m.licence!=='OGDL-1.0'||m.no_imputation!==true)throw Error('合法歷史快照 manifest 驗證未通過');if(v.schema_version<5||v.models?.holding_rules?.status!=='AVAILABLE_RULE_BASED')throw Error('持股規則狀態檔版本未通過');const c=coverage(m);if(internalSummary)internalSummary.textContent=`資料截止 ${m.last_date||'未取得'}｜入場 ${entryReady()?'已解鎖':'驗證中'}`;if(internalBody){const wrap=document.createElement('div');wrap.dataset.cutoffStatus='1';wrap.innerHTML=internalHtml(m,v);internalBody.prepend(wrap)}if(publicSummary)publicSummary.textContent=entryReady()?'入場模型已解鎖｜持倉規則可用':'入場模型驗證中｜持倉規則可用';if(publicBody)publicBody.innerHTML=readyHtml(m,v);window.StockLabDataStatus={manifest:m,validation:v,latestDate:m.last_date||null,modelReady:entryReady(),holdingRulesAvailable:true,coverage:c};}catch(e){const msg=String(e.message||e);if(internalSummary)internalSummary.textContent='資料截止日未驗證';if(publicSummary)publicSummary.textContent='入場資料待驗證｜持倉依當次合法快照';if(publicBody)publicBody.innerHTML=`<b class=bad>部分資料層未完成</b><div class=mini>${esc(msg)}。缺少資料維持缺少，不補值；已持有頁仍可在取得合法已驗證收盤後，以使用者部位做規則式風險管理。</div>`;window.StockLabDataStatus={manifest:null,validation:null,latestDate:null,modelReady:false,holdingRulesAvailable:false,error:msg};}}
  run();
})();
