// Quarterly financial quality layer. Official sources only: TWSE/MOPS + TPEx/MOPS OpenAPI.
const FIN_URL={
  listedIncome:`${OA}/v1/opendata/t187ap06_L_ci`,listedBalance:`${OA}/v1/opendata/t187ap07_L_ci`,
  otcIncome:`https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap06_O_ci`,otcBalance:`https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap07_O_ci`
};
let FINMAP=new Map();
const _extrasBase=extras,_combineBase=combine,_renderBase=render;
function pickNum(o,...keys){for(const k of keys){if(o&&o[k]!=null&&String(o[k]).trim()!==''){const x=n(o[k]);if(x!=null)return x}}return null}
async function finFetch(url){const h=new URL(url).hostname;if(h==='www.tpex.org.tw'){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('TPEx 季報連線失敗');return r.json()}return jget(url)}
function mergeFinRows(M,inc,bal,market){
  for(const x of inc||[]){const code=String(x['公司代號']||x['SecuritiesCompanyCode']||'').trim();if(!code)continue;const revenue=pickNum(x,'營業收入'),gross=pickNum(x,'營業毛利（毛損）淨額','營業毛利（毛損）'),op=pickNum(x,'營業利益（損失）'),net=pickNum(x,'本期淨利（淨損）','淨利（淨損）歸屬於母公司業主'),eps=pickNum(x,'基本每股盈餘（元）');M.set(code,{...(M.get(code)||{}),code,market,year:x['年度'],quarter:x['季別'],reportDate:x['出表日期'],revenue,gross,op,net,eps});}
  for(const x of bal||[]){const code=String(x['公司代號']||x['SecuritiesCompanyCode']||'').trim();if(!code)continue;const q=M.get(code)||{code,market,year:x['年度'],quarter:x['季別'],reportDate:x['出表日期']};q.currentAssets=pickNum(x,'流動資產');q.assets=pickNum(x,'資產總計');q.currentLiab=pickNum(x,'流動負債');q.liabilities=pickNum(x,'負債總計');q.equity=pickNum(x,'權益總計');q.bookValue=pickNum(x,'每股參考淨值');M.set(code,q);}
}
async function loadQuarterly(){try{
  const res=await Promise.allSettled([finFetch(FIN_URL.listedIncome),finFetch(FIN_URL.listedBalance),finFetch(FIN_URL.otcIncome),finFetch(FIN_URL.otcBalance)]),M=new Map();
  mergeFinRows(M,res[0].status==='fulfilled'?res[0].value:[],res[1].status==='fulfilled'?res[1].value:[],'TWSE');
  mergeFinRows(M,res[2].status==='fulfilled'?res[2].value:[],res[3].status==='fulfilled'?res[3].value:[],'TPEx');
  for(const [code,q] of M){q.grossMargin=q.revenue&&q.gross!=null?q.gross/q.revenue*100:null;q.opMargin=q.revenue&&q.op!=null?q.op/q.revenue*100:null;q.netMargin=q.revenue&&q.net!=null?q.net/q.revenue*100:null;q.debtRatio=q.assets&&q.liabilities!=null?q.liabilities/q.assets*100:null;q.currentRatio=q.currentLiab&&q.currentAssets!=null?q.currentAssets/q.currentLiab:null;}
  FINMAP=M;return M;
}catch(e){FINMAP=new Map();return FINMAP}}
function financialScore(q,h){if(!q||h==='day')return 0;let d=0;if(q.eps!=null){if(q.eps>0)d+=h==='long'?3:2;else if(q.eps<0)d-=h==='long'?4:3}if(q.opMargin!=null){if(q.opMargin>=15)d+=2;else if(q.opMargin<0)d-=3}if(q.grossMargin!=null&&q.grossMargin>=25)d+=1;if(q.debtRatio!=null){if(q.debtRatio<=50)d+=h==='long'?2:1;else if(q.debtRatio>=80)d-=h==='long'?4:2}if(q.currentRatio!=null){if(q.currentRatio>=1.5)d+=1;else if(q.currentRatio<0.8)d-=2}return Math.max(-8,Math.min(8,d))}
extras=async function(date){const base=await _extrasBase(date);await loadQuarterly();for(const [code,v] of base.V)v.code=code;for(const [code,r] of base.R)r.code=code;return base};
combine=function(a,h,m,v,i,r){a=_combineBase(a,h,m,v,i,r);const code=v?.code||r?.code||i?.code,q=code?FINMAP.get(code):null,fd=financialScore(q,h);a.fin=q;a.finDelta=fd;a.score=Math.max(0,Math.min(100,a.score+fd));a.action=a.score>=75?'偏多｜等拉回可分批':a.score>=60?'觀察｜不追價':a.score>=45?'中性｜等待確認':'偏弱｜暫避';return a};
render=function(code,a,h,vf){_renderBase(code,a,h,vf);if(!vf.complete)return;const q=a.fin;if(!q)return;const result=$('#result'),marker=result.querySelector('h3:last-of-type');const box=document.createElement('div');box.innerHTML=`<h3>季度財務品質</h3><div class=sourcegrid><div class=sourceitem><b>市場 / 期間</b>${q.market||'—'}｜${q.year||'—'} 年 Q${q.quarter||'—'}｜出表 ${q.reportDate||'—'}</div><div class=sourceitem><b>EPS</b>${q.eps!=null?fmt(q.eps):'—'}</div><div class=sourceitem><b>毛利率 / 營益率</b>${q.grossMargin!=null?q.grossMargin.toFixed(1)+'%':'—'} / ${q.opMargin!=null?q.opMargin.toFixed(1)+'%':'—'}</div><div class=sourceitem><b>淨利率</b>${q.netMargin!=null?q.netMargin.toFixed(1)+'%':'—'}</div><div class=sourceitem><b>負債比</b>${q.debtRatio!=null?q.debtRatio.toFixed(1)+'%':'—'}</div><div class=sourceitem><b>流動比</b>${q.currentRatio!=null?q.currentRatio.toFixed(2)+'x':'—'}</div><div class=sourceitem><b>財務品質調整</b>${a.finDelta>0?'+':''}${a.finDelta}</div><div class=sourceitem><b>來源</b>${q.market==='TPEx'?'TPEx/MOPS O_ci':'TWSE/MOPS L_ci'}</div></div>`;result.insertBefore(box,marker||null);const bubble=result.querySelector('.bubble');if(bubble)bubble.textContent=a.score;const mini=result.querySelector('.toprow .mini');if(mini)mini.innerHTML+=`｜季報 ${a.finDelta>0?'+':''}${a.finDelta}`;};