// Quarterly financial quality layer. Official OGDL sources. General-industry schema only in this file.
const FIN_URL={
  listedIncome:`${OA}/v1/opendata/t187ap06_L_ci`,listedBalance:`${OA}/v1/opendata/t187ap07_L_ci`,
  otcIncome:`https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap06_O_ci`,otcBalance:`https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap07_O_ci`
};
let FINMAP=new Map(),FIN_STATUS={};
const _extrasBase=extras,_combineBase=combine,_renderBase=render;
function pickNum(o,...keys){for(const k of keys){if(o&&o[k]!=null&&String(o[k]).trim()!==''){const x=n(o[k]);if(x!=null)return x}}return null}
async function finFetch(url){const h=new URL(url).hostname;if(h==='www.tpex.org.tw'){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('TPEx 季報連線失敗');return r.json()}return jget(url)}
function mergeIncome(M,rows,market){for(const x of rows||[]){const code=String(x['公司代號']||x['SecuritiesCompanyCode']||'').trim();if(!code)continue;const revenue=pickNum(x,'營業收入'),gross=pickNum(x,'營業毛利（毛損）淨額','營業毛利（毛損）'),op=pickNum(x,'營業利益（損失）'),net=pickNum(x,'本期淨利（淨損）','淨利（淨損）歸屬於母公司業主'),eps=pickNum(x,'基本每股盈餘（元）');const q=M.get(code)||{code,market,accountingClass:'general'};q.incomeObserved=true;q.incomeYear=String(x['年度']??'');q.incomeQuarter=String(x['季別']??'');q.incomeReportDate=x['出表日期']||null;q.revenue=revenue;q.gross=gross;q.op=op;q.net=net;q.eps=eps;M.set(code,q)}}
function mergeBalance(M,rows,market){for(const x of rows||[]){const code=String(x['公司代號']||x['SecuritiesCompanyCode']||'').trim();if(!code)continue;const q=M.get(code)||{code,market,accountingClass:'general'};q.balanceObserved=true;q.balanceYear=String(x['年度']??'');q.balanceQuarter=String(x['季別']??'');q.balanceReportDate=x['出表日期']||null;q.currentAssets=pickNum(x,'流動資產');q.assets=pickNum(x,'資產總計');q.currentLiab=pickNum(x,'流動負債');q.liabilities=pickNum(x,'負債總計');q.equity=pickNum(x,'權益總計');q.bookValue=pickNum(x,'每股參考淨值');M.set(code,q)}}
function finalizeFin(M){for(const [code,q] of M){q.samePeriod=!!(q.incomeObserved&&q.balanceObserved&&q.incomeYear&&q.incomeYear===q.balanceYear&&q.incomeQuarter&&q.incomeQuarter===q.balanceQuarter);q.year=q.samePeriod?q.incomeYear:null;q.quarter=q.samePeriod?q.incomeQuarter:null;q.reportDate=q.samePeriod?(q.incomeReportDate||q.balanceReportDate):null;q.completeStatements=q.samePeriod;q.provenance=q.samePeriod?'observed_complete_general_statements':'unavailable_incomplete_or_period_mismatch';q.grossMargin=q.completeStatements&&q.revenue&&q.gross!=null?q.gross/q.revenue*100:null;q.opMargin=q.completeStatements&&q.revenue&&q.op!=null?q.op/q.revenue*100:null;q.netMargin=q.completeStatements&&q.revenue&&q.net!=null?q.net/q.revenue*100:null;q.debtRatio=q.completeStatements&&q.assets&&q.liabilities!=null?q.liabilities/q.assets*100:null;q.currentRatio=q.completeStatements&&q.currentLiab&&q.currentAssets!=null?q.currentAssets/q.currentLiab:null;if(!q.completeStatements){q.eps=null;q.revenue=null;q.gross=null;q.op=null;q.net=null}}}
async function loadQuarterly(){const res=await Promise.allSettled([finFetch(FIN_URL.listedIncome),finFetch(FIN_URL.listedBalance),finFetch(FIN_URL.otcIncome),finFetch(FIN_URL.otcBalance)]),M=new Map();FIN_STATUS={listedIncome:res[0].status,listedBalance:res[1].status,otcIncome:res[2].status,otcBalance:res[3].status};mergeIncome(M,res[0].status==='fulfilled'?res[0].value:[],'TWSE');mergeBalance(M,res[1].status==='fulfilled'?res[1].value:[],'TWSE');mergeIncome(M,res[2].status==='fulfilled'?res[2].value:[],'TPEx');mergeBalance(M,res[3].status==='fulfilled'?res[3].value:[],'TPEx');finalizeFin(M);FINMAP=M;return M}
function financialScore(q,h){if(!q||!q.completeStatements||q.accountingClass!=='general'||h==='day')return 0;let d=0;if(q.eps!=null){if(q.eps>0)d+=h==='long'?3:2;else if(q.eps<0)d-=h==='long'?4:3}if(q.opMargin!=null){if(q.opMargin>=15)d+=2;else if(q.opMargin<0)d-=3}if(q.grossMargin!=null&&q.grossMargin>=25)d+=1;if(q.debtRatio!=null){if(q.debtRatio<=50)d+=h==='long'?2:1;else if(q.debtRatio>=80)d-=h==='long'?4:2}if(q.currentRatio!=null){if(q.currentRatio>=1.5)d+=1;else if(q.currentRatio<0.8)d-=2}return Math.max(-8,Math.min(8,d))}
extras=async function(date){const base=await _extrasBase(date);await loadQuarterly();for(const [code,v] of base.V)v.code=code;for(const [code,r] of base.R)r.code=code;return base};
combine=function(a,h,m,v,i,r){a=_combineBase(a,h,m,v,i,r);const code=v?.code||r?.code||i?.code,q=code?FINMAP.get(code):null,fd=financialScore(q,h);a.fin=q||null;a.finDelta=fd;a.finStatus=FIN_STATUS;a.score=Math.max(0,Math.min(100,a.score+fd));a.action=a.score>=75?'研究訊號偏多｜等待驗證與風險條件':a.score>=60?'研究訊號觀察｜不追價':a.score>=45?'研究訊號中性｜等待確認':'研究訊號偏弱｜暫避';return a};
render=function(code,a,h,vf){_renderBase(code,a,h,vf);if(!vf.complete)return;const q=a.fin;if(!q||!q.completeStatements)return;const result=$('#result'),marker=result.querySelector('h3:last-of-type');const box=document.createElement('div');box.innerHTML=`<h3>季度財務品質｜一般業 schema</h3><div class=sourcegrid><div class=sourceitem><b>市場 / 期間</b>${q.market||'—'}｜${q.year||'—'} 年 Q${q.quarter||'—'}｜出表 ${q.reportDate||'—'}</div><div class=sourceitem><b>EPS</b>${q.eps!=null?fmt(q.eps):'—'}</div><div class=sourceitem><b>毛利率 / 營益率</b>${q.grossMargin!=null?q.grossMargin.toFixed(1)+'%':'—'} / ${q.opMargin!=null?q.opMargin.toFixed(1)+'%':'—'}</div><div class=sourceitem><b>淨利率</b>${q.netMargin!=null?q.netMargin.toFixed(1)+'%':'—'}</div><div class=sourceitem><b>負債比</b>${q.debtRatio!=null?q.debtRatio.toFixed(1)+'%':'—'}</div><div class=sourceitem><b>流動比</b>${q.currentRatio!=null?q.currentRatio.toFixed(2)+'x':'—'}</div><div class=sourceitem><b>財務品質調整</b>${a.finDelta>0?'+':''}${a.finDelta}</div><div class=sourceitem><b>資料完整性</b>損益表＋資產負債表同年度同季度 ✅</div></div>`;result.insertBefore(box,marker||null);const bubble=result.querySelector('.bubble');if(bubble)bubble.textContent=a.score};
