// TAIFEX TX observation layer. Verified snapshot only; never alters stock scores here.
let TX_FUTURES=null;
function txAgeDays(s){if(!s)return 999;const d=new Date(String(s).replaceAll('/','-')+'T00:00:00+08:00');return Number.isNaN(d.getTime())?999:Math.floor((Date.now()-d.getTime())/86400000)}
function verifiedTX(x){if(!x||x.schema_version!==1||x.verified!==true)return{ok:false,why:'快照尚未驗證'};if(x.source!=='TAIFEX'||x.contract!=='TX')return{ok:false,why:'來源或契約不符'};if(!x.trade_date||txAgeDays(x.trade_date)>4)return{ok:false,why:'交易日期過舊'};if(!x.contract_month||!/^[0-9]{6}$/.test(String(x.contract_month)))return{ok:false,why:'契約月份格式異常'};if(!Number.isFinite(Number(x.last_price))||Number(x.last_price)<=0)return{ok:false,why:'最後成交價異常'};if(x.cross_check!=='matched')return{ok:false,why:'TAIFEX 雙頁交叉比對未通過'};if(!x.raw_sha256?.report||!x.raw_sha256?.excel)return{ok:false,why:'缺少原始內容雜湊'};return{ok:true,why:'verified'}}
async function loadTX(){try{const r=await fetch('./futures-data.json',{cache:'no-store'});if(!r.ok)throw Error('futures-data unavailable');TX_FUTURES=await r.json();return TX_FUTURES}catch(e){TX_FUTURES={status:'unavailable',verified:false,error:String(e.message||e)};return TX_FUTURES}}
function txPanel(){const v=verifiedTX(TX_FUTURES);if(!v.ok)return `<h3>台指期 TX</h3><div class=sourceitem><b>⚠️ 未納入</b><span class=mini>${v.why}；略過、不補值</span></div>`;const p=Number(TX_FUTURES.change_pct);return `<h3>台指期 TX</h3><div class=sourcegrid><div class=sourceitem><b>契約／價格</b>${TX_FUTURES.contract_month}｜${fmt(TX_FUTURES.last_price)} ${Number.isFinite(p)?`｜${p>0?'+':''}${p.toFixed(2)}%`:''}</div><div class=sourceitem><b>成交量／OI</b>${fmt(TX_FUTURES.total_volume)}／${fmt(TX_FUTURES.open_interest)}<br><span class=mini>${TX_FUTURES.trade_date}｜TAIFEX 雙頁一致</span></div></div><div class=mini style="margin-top:8px">目前只作市場觀察，不改變個股或選股分數。</div>`}
const _txShowMarket=showMarket;
showMarket=function(m){_txShowMarket(m);const target=document.querySelector('#marketDetailsBody');if(!target)return;let box=target.querySelector('[data-tx-market]');if(!box){box=document.createElement('div');box.dataset.txMarket='1';target.appendChild(box)}box.innerHTML=txPanel()};
loadTX();
