// TAIFEX TX observation layer. Verified snapshot only; does not affect scores yet.
let TX_FUTURES=null;
function txAgeDays(s){if(!s)return 999;const d=new Date(String(s).replaceAll('/','-')+'T00:00:00+08:00');return Number.isNaN(d.getTime())?999:Math.floor((Date.now()-d.getTime())/86400000)}
function verifiedTX(x){if(!x||x.schema_version!==1||x.verified!==true)return{ok:false,why:'TAIFEX 快照尚未驗證'};if(x.source!=='TAIFEX'||x.contract!=='TX')return{ok:false,why:'來源或契約不符'};if(!x.trade_date||txAgeDays(x.trade_date)>4)return{ok:false,why:'交易日期過舊'};if(!x.contract_month||!/^[0-9]{6}$/.test(String(x.contract_month)))return{ok:false,why:'契約月份格式異常'};if(!Number.isFinite(Number(x.last_price))||Number(x.last_price)<=0)return{ok:false,why:'最後成交價異常'};if(x.cross_check!=='matched')return{ok:false,why:'TAIFEX 雙頁交叉比對未通過'};if(!x.raw_sha256?.report||!x.raw_sha256?.excel)return{ok:false,why:'缺少原始內容雜湊'};return{ok:true,why:'verified'}}
async function loadTX(){try{const r=await fetch('./futures-data.json',{cache:'no-store'});if(!r.ok)throw Error('futures-data.json unavailable');TX_FUTURES=await r.json();return TX_FUTURES}catch(e){TX_FUTURES={status:'unavailable',verified:false,error:String(e.message||e)};return TX_FUTURES}}
function txPanel(){const v=verifiedTX(TX_FUTURES);if(!v.ok)return `<h3>台指期 TX｜觀察層</h3><div class=sourcegrid><div class=sourceitem><b>⚠️ 未驗證</b>${v.why}，不計分</div></div>`;const p=Number(TX_FUTURES.change_pct);return `<h3>台指期 TX｜觀察層</h3><div class=sourcegrid><div class=sourceitem><b>契約</b>${TX_FUTURES.contract_month}</div><div class=sourceitem><b>最後成交價</b>${fmt(TX_FUTURES.last_price)}｜${Number.isFinite(p)?`${p>0?'+':''}${p.toFixed(2)}%`:'—'}</div><div class=sourceitem><b>成交量 / OI</b>${fmt(TX_FUTURES.total_volume)} / ${fmt(TX_FUTURES.open_interest)}</div><div class=sourceitem><b>資料日</b>${TX_FUTURES.trade_date}<br><span class=mini>TAIFEX 雙頁一致｜抓取 ${String(TX_FUTURES.generated_at||'—').replace('T',' ').slice(0,19)} UTC</span></div></div><p class=muted>台指期目前只作市場觀察，不改變個股或 TOP 10 分數。</p>`}
const _txShowMarket=showMarket;
showMarket=function(m){_txShowMarket(m);const box=document.createElement('div');box.innerHTML=txPanel();$('#marketBody').appendChild(box)};
loadTX();
