// Single-stock entry router. One decision only: whether the stock is suitable to enter.
// Short/mid/long buy bands are forbidden. The model requires the same nine factors + US market + TX futures + international events.
(function(){
  const btn=document.querySelector('#analyzeBtn');if(!btn)return;
  const MISSING='資料未取得／未通過驗證';
  function tickSize(p){if(p<10)return .01;if(p<50)return .05;if(p<100)return .1;if(p<500)return .5;if(p<1000)return 1;return 5}
  function roundTick(p,mode='nearest'){const t=tickSize(Math.max(.01,p)),q=p/t,z=mode==='down'?Math.floor(q):mode==='up'?Math.ceil(q):Math.round(q);return +(z*t).toFixed(t<.1?2:t<1?1:0)}
  function qtile(a,q){const v=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!v.length)return null;const p=(v.length-1)*q,l=Math.floor(p),h=Math.ceil(p);return l===h?v[l]:v[l]+(v[h]-v[l])*(p-l)}
  function openingGapStats(r,look=60){if(!r||r.length<60)throw Error('買入模型有效日線不足 60 根');const z=[],start=Math.max(1,r.length-look);for(let i=start;i<r.length;i++){const pc=r[i-1].c,o=r[i].o;if(Number.isFinite(pc)&&pc>0&&Number.isFinite(o)&&o>0)z.push(o/pc-1)}if(z.length<40)throw Error(`隔夜開盤有效樣本不足：${z.length}/40`);return{n:z.length,q25:qtile(z,.25),q50:qtile(z,.50),q75:qtile(z,.75),provenance:'derived'}}
  function intradayPullbackStats(r,look=60){if(!r||r.length<60)throw Error('盤中回檔模型有效日線不足 60 根');const lows=[];for(const x of r.slice(-look))if(Number.isFinite(x.o)&&x.o>0&&Number.isFinite(x.l)&&x.l>0)lows.push(x.l/x.o-1);if(lows.length<40)throw Error(`盤中回檔有效樣本不足：${lows.length}/40`);return{n:lows.length,q25:qtile(lows,.25),q50:qtile(lows,.50),provenance:'derived'}}
  function taipeiClock(){const p={};for(const x of new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()))p[x.type]=x.value;const mins=Number(p.hour)*60+Number(p.minute),business=!['Sat','Sun'].includes(p.weekday);let phase='closed';if(business&&mins<510)phase='before-orders';else if(business&&mins<540)phase='preopen';else if(business&&mins<805)phase='continuous';else if(business&&mins<810)phase='closing-auction';return{date:`${p.year}-${p.month}-${p.day}`,mins,weekday:p.weekday,business,phase}}
  function targetContext(dataDate){const now=taipeiClock(),sameDate=dataDate===now.date,phaseLabel={'before-orders':'目前台北時間尚未到 08:30',preopen:'目前為 08:30–09:00 盤前委託時段',continuous:'目前為 09:00–13:25 盤中逐筆交易時段','closing-auction':'目前為 13:25–13:30 收盤集合競價時段',closed:'目前非一般盤交易時段'}[now.phase],dataLabel=sameDate?'最新已驗證資料已包含今日收盤；新計畫只適用於下一交易日':'最新已驗證資料尚未包含今日收盤；不因時鐘已過 09:00 或 13:30 就自動假定今日收盤資料已取得';return{now,sameDate,targetLabel:`基準交易日 ${dataDate} 之後的下一交易日`,phaseLabel,dataLabel,provenance:'derived'}}
  function buildBuyPlan(r){const L=r?.at(-1);if(!L||!Number.isFinite(L.c))throw Error('買入模型缺少最新已驗證收盤');const gap=openingGapStats(r),pull=intradayPullbackStats(r),target=targetContext(L.iso),expectedOpen=L.c*(1+gap.q50),preopenLimit=roundTick(expectedOpen),a=expectedOpen*(1+pull.q25),b=expectedOpen*(1+pull.q50),waitLow=roundTick(Math.min(a,b),'up'),waitHigh=roundTick(Math.max(a,b),'down');return{model:'TW-next-session-entry-v2',baseDate:L.iso,baseClose:L.c,target,gap,pull,preopenLimit,waitLow,waitHigh:waitHigh<waitLow?waitLow:waitHigh,expectedOpenRange:[roundTick(L.c*(1+gap.q25),'up'),roundTick(L.c*(1+gap.q75),'down')],provenance:{baseClose:'observed',gap:'derived',pullback:'derived',preopenLimit:'model_estimate',waitZone:'model_estimate'}}}
  function stateIcon(s){return s==='positive'?'✅':s==='negative'?'⚠️':s==='neutral'?'➖':'⛔'}
  function factorGrid(entry){const f=entry?.factors||{};return (window.StockLabEntryDecision?.factorList?.()||[]).map(x=>{const z=f[x.key]||{};return `<div class=sourceitem><b>${stateIcon(z.state)} ${x.label}</b><span class=mini>${z.verified?z.evidence:MISSING}</span></div>`}).join('')}
  function contextGrid(entry){const c=entry?.contexts||{},row=(name,z)=>`<div class=sourceitem><b>${z?.verified?'✅':'⛔'} ${name}</b><span class=mini>${z?.verified?`${z.state}｜${z.reason||''}`:(z?.reason||MISSING)}</span></div>`;return row('美股',c.us)+row('台指期 TX',c.tx)+row('國際時事',c.events)}
  function productionGate(a,vf,entry){const rt=window.STOCKLAB_RUNTIME||{},reasons=[];if(rt.gates?.licensedHistoricalOHLC!==true)reasons.push('合法歷史 OHLC Gate 未通過');if(rt.gates?.securityMaster!==true)reasons.push('商品分類 Gate 未通過');if(rt.gates?.tradingCalendar!==true)reasons.push('台股交易日曆 Gate 未通過');if(rt.gates?.corporateActions!==true)reasons.push('公司行動／參考價 Gate 未通過');if(rt.gates?.taiwanRiskState!==true)reasons.push('注意／處置／特殊交易狀態 Gate 未通過');if(rt.gates?.entryNineFactors!==true)reasons.push('九項入場因子 Gate 未通過');if(rt.gates?.usMarketContext!==true)reasons.push('美股背景 Gate 未通過');if(rt.gates?.txFuturesContext!==true)reasons.push('台指期 Gate 未通過');if(rt.gates?.internationalEventFeed!==true)reasons.push('國際時事 Gate 未通過');if(rt.gates?.entryDecisionOosValidation!==true)reasons.push('統一入場模型正式 OOS Gate 未通過');if(!vf?.complete)reasons.push('最新官方收盤交叉驗證未通過');if(entry?.summary?.complete!==true)reasons.push('九項因子或三個市場背景仍有缺漏');if(a?.riskBlocked)reasons.push('個股台股風險 Gate 阻擋');return{ok:reasons.length===0,reasons}}
  function renderBuy(code,marketName,a,vf,r){
    const box=document.querySelector('#result'),label=a.stockName?`${a.stockName}／${code}`:code;if(!vf.complete){box.innerHTML=`<div class=toprow><div><h2>${label}</h2><div class=muted>${marketName}｜入場判斷</div></div></div><h3 class=bad>⛔ 資料驗證未通過</h3><p>${vf.text||'最新官方價格無法交叉驗證'}</p>`;box.classList.remove('hidden');return}
    const entry=window.StockLabEntryDecision?.evaluate?window.StockLabEntryDecision.evaluate(r,a):null,plan=buildBuyPlan(r),gate=productionGate(a,vf,entry),s=entry?.summary||{positive:0,neutral:0,negative:0,complete:false};
    const preopenNow=gate.ok&&plan.target.now.phase==='preopen'&&!plan.target.sameDate,preopenStatus=preopenNow?'目前位於盤前限價 ROD 執行窗口':'模型計畫值；不是目前即時成交價',dayStatus=plan.target.now.phase==='continuous'?'公開版沒有合法即時行情，盤中是否已到價未知；禁止把前一完成交易日模型值冒充目前可買價':'只在所有 Gate 通過時作下一交易時段條件參考';
    box.innerHTML=`<div data-buy-plan="1" class=toprow><div><h2>${label}</h2><div class=muted>${marketName}｜是否適合入場</div><div class=mini>官方基準 ${plan.baseDate} 收盤 ${fmt(plan.baseClose)}｜${plan.target.targetLabel}</div></div><div><div class=bubble>${s.positive}/9</div><div class=mini style="text-align:center">正向因子／9<br>不是機率</div></div></div>
      <div class=source-note><b>${gate.ok?'完整入場判斷可執行':'⛔ 完整入場判斷目前被阻擋'}</b><div class=mini>${gate.ok?'所有必要資料與 OOS Gate 已通過。':gate.reasons.join('；')}<br>${plan.target.dataLabel}<br>${plan.target.phaseLabel}</div></div>
      <h3>九項入場判斷</h3><div class=sourcegrid>${factorGrid(entry)}</div>
      <h3>美股／台指期／國際時事</h3><div class=sourcegrid>${contextGrid(entry)}</div>
      <h3>下一交易時段價格計畫</h3><div class=sourcegrid><div class=sourceitem><b>盤前限價 ROD 模型值</b><div style="font-size:24px;font-weight:900;margin-top:4px">${gate.ok?fmt(plan.preopenLimit):MISSING}</div><span class=mini>${preopenStatus}</span></div><div class=sourceitem><b>盤中等待區</b><div style="font-size:24px;font-weight:900;margin-top:4px">${gate.ok?`${fmt(plan.waitLow)}–${fmt(plan.waitHigh)}`:MISSING}</div><span class=mini>${dayStatus}</span></div></div>
      <h3>資料與推估分離</h3><div class=sourcegrid><div class=sourceitem><b>最新已驗證收盤｜observed</b>${plan.baseDate}｜${fmt(plan.baseClose)}</div><div class=sourceitem><b>隔夜跳空統計｜derived</b>樣本 ${plan.gap.n}｜Q25 ${(plan.gap.q25*100).toFixed(2)}%｜中位數 ${(plan.gap.q50*100).toFixed(2)}%｜Q75 ${(plan.gap.q75*100).toFixed(2)}%</div><div class=sourceitem><b>預估開盤區間｜model_estimate</b>${gate.ok?`${fmt(plan.expectedOpenRange[0])}–${fmt(plan.expectedOpenRange[1])}`:MISSING}</div><div class=sourceitem><b>台股風險狀態</b>${(a.taiwanRisk?.flags||[]).join('｜')||MISSING}</div></div>
      <div class=disclaimer><b>入場模型規則</b>九項因子與美股、台指期、國際時事是同一套完整判斷。任何必要來源缺漏都不能用 0、前期值、其他網站、AI 或推估值補入。頁面不再產生短／中／長買入價。</div>`;box.classList.remove('hidden')
  }
  function renderPrivate(j){
    const hp=window.StockLabHardPolicy?.backendResult?.(j,'analysis');if(hp&&hp.ok!==true)throw Error(`後端結果未通過硬規則：${hp.blockers.join('；')}`);
    const d=j.data||{},box=document.querySelector('#result'),label=d.name?`${d.name}／${d.ticker||'—'}`:(d.ticker||'—'),f=d.entry_factors||{},vals=Object.values(f),positive=vals.filter(x=>x?.state==='positive').length,entry=d.entry_price!=null?fmt(d.entry_price):MISSING;
    const fac=(window.StockLabEntryDecision?.factorList?.()||[]).map(x=>{const z=f[x.key]||{};return `<div class=sourceitem><b>${stateIcon(z.state)} ${x.label}</b><span class=mini>${z.verified?z.evidence:MISSING}</span></div>`}).join(''),ctx={factors:f,contexts:d.market_context||{}};
    box.innerHTML=`<div class=toprow><div><h2>${label}</h2><div class=muted>${d.exchange||'—'}｜入場判斷｜私有分析引擎</div><div class=mini>資料日 ${d.data_date||'—'}｜模型 ${j.model_version||'—'}</div></div><div><div class=bubble>${positive}/9</div><div class=mini>正向因子／9<br>不是機率</div></div></div><div class=source-note><b>${d.action||'入場判斷'}</b><div style="font-size:24px;font-weight:900;margin-top:4px">${entry}</div></div><h3>九項入場判斷</h3><div class=sourcegrid>${fac}</div><h3>美股／台指期／國際時事</h3><div class=sourcegrid>${contextGrid(ctx)}</div>`;box.classList.remove('hidden')
  }
  async function localAnalyze(code){
    const loader=window.StockLabLicensedHistory;if(!loader?.load)throw Error('合法歷史行情介面尚未接入；禁止改用未授權網站歷史資料補值');
    const [twSnap,tpSnap]=await Promise.all([jget(U.snap),window.StockLabTPEx?window.StockLabTPEx.tpexSnapshot().catch(()=>[]):Promise.resolve([])]),twRow=twSnap.find(x=>String(x.Code)===code),otcRow=tpSnap.find(x=>x.code===code);if(!twRow&&!otcRow)throw Error('合法公開資料中找不到此代號');
    const marketName=otcRow&&!twRow?'TPEx':'TWSE',r=await loader.load({code,market:marketName,minimumBars:60});if(!Array.isArray(r)||r.length<60)throw Error('合法歷史行情不足');
    const vf=marketName==='TWSE'?await verify(code,r):await window.StockLabTPEx.verifyTpex(code,r,otcRow);if(window.StockLabTaiwan?.loadFactors)await window.StockLabTaiwan.loadFactors();
    const a=tech(r);a.exchange=marketName;a.stockName=twRow?.Name||otcRow?.name||'';a.integrity={price:{ok:vf.complete},institution:{ok:false}};a.inst=null;
    const risk=window.StockLabTaiwan?.riskState?window.StockLabTaiwan.riskState(code,marketName):{flags:['台股風險狀態未取得'],riskBlocked:false,verified:false};a.industry=risk.industry||null;a.sectorFamily=window.StockLabTaiwan?.sectorFamily?window.StockLabTaiwan.sectorFamily(a.industry):null;a.riskBlocked=risk.riskBlocked===true;a.taiwanRisk=risk;
    if(marketName==='TPEx'&&window.StockLabTPEx){try{const e=await window.StockLabTPEx.tpexExtras(),i=e.I.get(code);if(i&&i.date===vf.date){a.inst=i;a.integrity.institution={ok:true,date:i.date}}}catch{}}
    renderBuy(code,marketName,a,vf,r)
  }
  btn.onclick=async()=>{const code=document.querySelector('#ticker').value.trim();if(!/^\d{4,6}$/.test(code))return alert('請輸入股票代號');document.querySelector('#singleLoad').classList.remove('hidden');try{const api=window.StockLabAPI;if(api?.config?.enabled){try{const j=await api.analyze(code);renderPrivate(j);return}catch(e){if(!api.config.allowLocalFallback)throw e}}await localAnalyze(code)}catch(e){const box=document.querySelector('#result');box.innerHTML=`<h3 class=bad>⛔ 無法形成完整入場判斷</h3><p>${e.message}</p><div class=disclaimer><b>NO IMPUTATION</b>缺資料、授權不明、來源失敗或驗證失敗時，StockLab 只回報缺口，不以任何假資訊補值。</div>`;box.classList.remove('hidden')}finally{document.querySelector('#singleLoad').classList.add('hidden')}};
})();
