// Single-stock router. Private backend is preferred; local engine exists only as migration fallback.
(function(){
  const btn=document.querySelector('#analyzeBtn');if(!btn)return;
  function tickSize(p){if(p<10)return .01;if(p<50)return .05;if(p<100)return .1;if(p<500)return .5;if(p<1000)return 1;return 5}
  function roundTick(p,mode='nearest'){const t=tickSize(Math.max(.01,p)),q=p/t,z=mode==='down'?Math.floor(q):mode==='up'?Math.ceil(q):Math.round(q);return +(z*t).toFixed(t<.1?2:t<1?1:0)}
  function atr14(r){if(r.length<15)return null;const a=[];for(let i=r.length-14;i<r.length;i++){const p=r[i-1].c,x=r[i];a.push(Math.max(x.h-x.l,Math.abs(x.h-p),Math.abs(x.l-p)))}return avg(a)}
  function qtile(a,q){const v=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!v.length)return null;const p=(v.length-1)*q,l=Math.floor(p),h=Math.ceil(p);return l===h?v[l]:v[l]+(v[h]-v[l])*(p-l)}
  function median(a){return qtile(a,.5)}
  function dayEntryPlan(r){if(!r?.length)throw Error('當日價格模型缺少歷史資料');const L=r.at(-1),cl=r.map(x=>x.c),ma5=avg(cl.slice(-5)),ma10=avg(cl.slice(-10)),w5=r.slice(-5),w10=r.slice(-10),w20=r.slice(-20),a=atr14(r);if(!ma5||!ma10||!a||w20.length<15)throw Error('當日入場模型資料不足');const low5=Math.min(...w5.map(x=>x.l)),low10=Math.min(...w10.map(x=>x.l)),lowQ=qtile(w20.map(x=>x.l),.25),cands=[ma5,ma10,low5,low10,lowQ].filter(x=>Number.isFinite(x)&&x<=L.c+a*.5),anchor=median(cands);if(anchor==null||lowQ==null)throw Error('當日支撐結構不足');let lo=Math.max(.01,lowQ,Math.min(anchor,low10)-a*.15),hi=Math.min(L.c,Math.max(anchor,low5)+a*.15);if(lo>hi){lo=Math.min(anchor,L.c);hi=Math.max(lo,Math.min(L.c,anchor+a*.1))}lo=roundTick(lo,'up');hi=roundTick(hi,'down');if(lo>hi)hi=lo;return{entryLow:lo,entryHigh:hi,support:roundTick(anchor),resist:roundTick(Math.max(...w10.map(x=>x.h))),atr:a,ma5,ma10,priceModel:'TW-day-structure-volatility-v4'}}
  function preopenPlan(r,a){const L=r.at(-1),day=dayEntryPlan(r),atr=day.atr,w10=r.slice(-10),w20=r.slice(-20),resist10=Math.max(...w10.map(x=>x.h)),resist20=Math.max(...w20.map(x=>x.h)),bias=a.score>=65?'偏多':a.score<45?'偏空':'震盪',confidence=Math.max(35,Math.min(85,Math.round(50+Math.abs(a.score-50)*.7))),mid=(day.entryLow+day.entryHigh)/2;let orderPrice=null;if(a.score>=65)orderPrice=roundTick(mid);else if(a.score>=45)orderPrice=roundTick(day.entryLow,'up');return{close:L.c,date:L.iso,orderPrice,day,stop:roundTick(Math.max(.01,day.support-atr*.45),'down'),target1:roundTick(Math.max(resist10,L.c+atr*.7),'down'),target2:roundTick(Math.max(resist20,L.c+atr*1.4),'down'),bias,confidence,ma5:day.ma5,ma10:day.ma10,atr,support10:Math.min(...w10.map(x=>x.l)),resist10}}
  function safeBand(r,h){try{return window.StockLabTaiwan?.adaptiveBand?window.StockLabTaiwan.adaptiveBand(r,h):null}catch{return null}}
  function bandText(x){return x&&x.entryLow!=null&&x.entryHigh!=null?`${fmt(x.entryLow)}–${fmt(x.entryHigh)}`:'—'}
  function fivePricePlan(r,a){const pre=preopenPlan(r,a);return{pre,day:pre.day,short:safeBand(r,'1m'),mid:safeBand(r,'3m'),long:safeBand(r,'long')}}
  function renderPreopen(code,marketName,a,vf,r){const box=document.querySelector('#result'),label=a.stockName?`${a.stockName}／${code}`:code;if(!vf.complete){box.innerHTML=`<div class=toprow><div><h2>${label}</h2><div class=muted>${marketName}｜開盤前｜當日掛單價格</div></div></div><h3 class=bad>⛔ 資料驗證未通過</h3><p>日期 ${vf.date||'—'}｜${vf.text||'無法交叉驗證'}</p>`;box.classList.remove('hidden');return}const p=fivePricePlan(r,a),pre=p.pre,blocked=!!a.riskBlocked,prePrice=blocked?'⛔ 不掛單':pre.orderPrice==null?'等待／不預掛':fmt(pre.orderPrice),preNote=blocked?'處置股或台股風險 Gate 阻擋':pre.orderPrice==null?'評分偏弱，不強制產生買單':'08:30–09:00 僅限價 ROD；09:00 集合競價';box.innerHTML=`<div class=toprow><div><h2>${label}</h2><div class=muted>${marketName}｜開盤前｜當日掛單價格</div><div class=mini>資料日 ${pre.date}｜${pre.bias}｜策略信心 ${pre.confidence}/100</div></div><div class=bubble>${a.score}</div></div><div data-five-price-matrix="1"><h3>五種價格</h3><div class=sourcegrid><div class=sourceitem><b>① 開盤前掛單價格</b><div style="font-size:24px;font-weight:900;margin-top:4px">${prePrice}</div><span class=mini>${preNote}</span></div><div class=sourceitem><b>② 當日入場適合區間</b><div style="font-size:24px;font-weight:900;margin-top:4px">${bandText(p.day)}</div><span class=mini>5／10／20日支撐結構＋ATR；非盤中即時訊號</span></div><div class=sourceitem><b>③ 短線入場區間</b><div style="font-size:24px;font-weight:900;margin-top:4px">${bandText(p.short)}</div><span class=mini>約1個月｜20日結構＋波動</span></div><div class=sourceitem><b>④ 中期入場區間</b><div style="font-size:24px;font-weight:900;margin-top:4px">${bandText(p.mid)}</div><span class=mini>約3個月｜60日結構＋波動</span></div><div class=sourceitem><b>⑤ 長期佈局區間</b><div style="font-size:24px;font-weight:900;margin-top:4px">${bandText(p.long)}</div><span class=mini>1年以上｜長週期結構＋基本面／估值 Gate</span></div></div></div><div class=kpis><div class=kpi><b>${fmt(pre.close)}</b><span>前一交易日收盤</span></div><div class=kpi><b>${fmt(pre.stop)}</b><span>當日停損參考</span></div><div class=kpi><b>${fmt(pre.target1)}</b><span>第一目標</span></div><div class=kpi><b>${fmt(pre.target2)}</b><span>第二目標</span></div></div><h3>開盤前價格依據</h3><div class=sourcegrid><div class=sourceitem><b>MA5 / MA10</b>${fmt(pre.ma5)} / ${fmt(pre.ma10)}</div><div class=sourceitem><b>10日支撐 / 壓力</b>${fmt(pre.support10)} / ${fmt(pre.resist10)}</div><div class=sourceitem><b>ATR14</b>${fmt(pre.atr)}</div><div class=sourceitem><b>台股風險 Gate</b>${(a.taiwanRisk?.flags||[]).join('｜')||'無注意／處置／信用交易異常旗標'}</div></div><div class=disclaimer><b>開盤前委託規則</b>08:30–09:00 的建議價格只對應「限價 ROD」委託；不把市價、IOC 或 FOK 當成開盤前可用委託。價格以最新已驗證日線與台股升降單位計算，重大跳空或事件發生時應重新評估。</div>`;box.classList.remove('hidden')}
  function renderPrivate(j){const d=j.data||{},box=document.querySelector('#result'),label=d.name?`${d.name}／${d.ticker||'—'}`:(d.ticker||'—'),entry=d.entry_low!=null&&d.entry_high!=null?`${fmt(d.entry_low)}–${fmt(d.entry_high)}`:'—';box.innerHTML=`<div class=toprow><div><h2>${label}</h2><div class=muted>${d.exchange||'—'}｜${d.horizon||'—'}｜私有分析引擎</div><div class=mini>${d.action||'資料不足'}｜模型版本 ${j.model_version||'—'}｜資料完整度 ${d.completeness??'—'}%</div></div><div class=bubble>${d.score??'—'}</div></div><div class=source-note><b>建議入場價格區間</b><div style="font-size:24px;font-weight:900;margin-top:4px">${entry}</div></div>`;box.classList.remove('hidden')}
  async function localAnalyze(code,h){const tp=window.StockLabTPEx,[twSnap,tpSnap,ir]=await Promise.all([jget(U.snap),tp?tp.tpexSnapshot().catch(()=>[]):Promise.resolve([]),ihist(6)]),m=market(ir);showMarket(m);const twRow=twSnap.find(x=>String(x.Code)===code),otcRow=tpSnap.find(x=>x.code===code);if(!twRow&&!otcRow)throw Error('官方上市／上櫃快照找不到此代號，或該市場資料健康驗證未通過');let r,vf,e,marketName;const modelH=h==='preopen'?'day':h;if(otcRow&&!twRow){marketName='TPEx';r=await tp.tpexHist(code,h==='long'?12:6);if(!r.length)throw Error('TPEx 歷史行情不足或來源未通過');vf=await tp.verifyTpex(code,r,otcRow);e=await tp.tpexExtras()}else{marketName='TWSE';r=await hist(code,h==='long'?12:6);if(!r.length)throw Error('TWSE 歷史行情不足');vf=await verify(code,r);e=await extras(r.at(-1).iso)}if(window.StockLabTaiwan?.loadFactors)await window.StockLabTaiwan.loadFactors();const a=combine(tech(r,modelH),modelH,m,e.V.get(code),e.I.get(code),e.R.get(code));a.exchange=marketName;a.stockName=twRow?.Name||otcRow?.name||'';if(h==='preopen'){renderPreopen(code,marketName,a,vf,r);return}render(code,a,h,vf);const result=document.querySelector('#result');if(result&&vf.complete){const title=result.querySelector('.toprow h2');if(title)title.textContent=`${a.stockName?`${a.stockName}／`:''}${code}`;const head=result.querySelector('.toprow .muted');if(head)head.textContent=`${marketName}｜${h}｜過渡本地引擎`;const firstKpi=result.querySelector('.kpis');if(firstKpi){const entry=`${fmt(a.entryLow)}–${fmt(a.entryHigh)}`;firstKpi.insertAdjacentHTML('beforebegin',`<div class=source-note><b>建議入場價格區間</b><div style="font-size:24px;font-weight:900;margin-top:4px">${entry}</div><div class=mini>${a.action}</div></div>`)}}}
  btn.onclick=async()=>{const code=document.querySelector('#ticker').value.trim(),h=document.querySelector('#horizon').value;if(!/^\d{4,6}$/.test(code))return alert('請輸入股票代號');document.querySelector('#singleLoad').classList.remove('hidden');try{const api=window.StockLabAPI;if(h!=='preopen'&&api?.config?.enabled){try{const j=await api.analyze(code,h);renderPrivate(j);return}catch(e){if(!api.config.allowLocalFallback)throw e}}await localAnalyze(code,h)}catch(e){document.querySelector('#result').innerHTML=`<h3 class=bad>分析失敗</h3><p>${e.message}</p>`;document.querySelector('#result').classList.remove('hidden')}finally{document.querySelector('#singleLoad').classList.add('hidden')}};
})();