// TPEx licensed-open-data adapter. No direct website-history collection is allowed here.
const TPA='https://www.tpex.org.tw/openapi/v1';
const TPU={snap:`${TPA}/tpex_mainboard_daily_close_quotes`,val:`${TPA}/tpex_mainboard_peratio_analysis`,inst:`${TPA}/tpex_3insti_daily_trading`,rev:`${TPA}/mopsfin_t187ap05_O`};
let TPHEALTH=null;
async function tpexHealth(force=false){if(TPHEALTH&&!force)return TPHEALTH;try{const r=await fetch('./tpex-health.json',{cache:'no-store'});if(!r.ok)throw Error('健康快照讀取失敗');const x=await r.json(),age=x.generated_at?Math.floor((Date.now()-new Date(x.generated_at).getTime())/864e5):999;TPHEALTH={...x,fresh:age<=4,usable:x.schema_version===1&&x.source==='TPEx'&&x.verified===true&&x.status==='ok'&&age<=4}}catch(e){TPHEALTH={verified:false,usable:false,status:'failed',error:String(e.message||e)}}return TPHEALTH}
async function requireTpexHealth(){const h=await tpexHealth();if(!h.usable)throw Error(`TPEx 資料健康驗證未通過：${h.status||'unknown'}${h.error?'｜'+h.error:''}`);return h}
// same-origin-cache.js replaces this function. Direct remote fallback is intentionally forbidden.
async function tpGet(){throw Error('合法 TPEx 同網域資料介面尚未初始化；禁止直接改抓 TPEx 網站補值')}
function pv(o,keys){for(const k of keys){if(o&&o[k]!=null&&String(o[k]).trim()!=='')return o[k]}return null}
function pn(o,keys){const v=pv(o,keys);return v==null?null:n(v)}
function tpIso(v){const s=String(v||'').replace(/\D/g,'');if(/^\d{7}$/.test(s))return `${+s.slice(0,3)+1911}-${s.slice(3,5)}-${s.slice(5,7)}`;if(/^\d{8}$/.test(s))return `${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`;const m=String(v||'').match(/(\d{2,3})\/(\d{2})\/(\d{2})/);return m?`${+m[1]+1911}-${m[2]}-${m[3]}`:null}
async function tpexSnapshot(){const rows=await tpGet(TPU.snap);if(!Array.isArray(rows))throw Error('TPEx 行情格式異常');return rows.map(x=>({market:'TPEx',code:String(pv(x,['SecuritiesCompanyCode','Code','證券代號','代號'])||'').trim(),name:String(pv(x,['CompanyName','SecuritiesCompanyName','Name','證券名稱','名稱'])||'').trim(),c:pn(x,['Close','ClosingPrice','收盤價','收盤']),v:pn(x,['TransactionAmount','TradeValue','TradingAmount','成交金額']),date:tpIso(pv(x,['Date','日期'])),provenance:'observed'})).filter(x=>/^\d{4}$/.test(x.code)&&Number.isFinite(x.c)&&Number.isFinite(x.v)&&x.date)}
async function tpexExtras(){const [vals,insts,revs]=await Promise.all([tpGet(TPU.val),tpGet(TPU.inst),tpGet(TPU.rev)]),V=new Map(),I=new Map(),R=new Map();for(const x of vals||[]){const code=String(pv(x,['SecuritiesCompanyCode','Code','證券代號','公司代號'])||'').trim();if(!code)continue;V.set(code,{code,pe:pn(x,['PriceEarningRatio','PERatio','本益比']),pb:pn(x,['PriceBookRatio','PBRatio','股價淨值比']),yield:pn(x,['YieldRatio','DividendYield','殖利率']),date:tpIso(pv(x,['Date','日期']))||pv(x,['Date','日期']),provenance:'observed'})}for(const x of insts||[]){const code=String(pv(x,['SecuritiesCompanyCode','Code','證券代號','公司代號'])||'').trim();if(!code)continue;const foreign=pn(x,['ForeignAndMainlandInvestorsBuySell','ForeignInvestorsBuySell','外資及陸資買賣超股數','外陸資買賣超股數']),trust=pn(x,['InvestmentTrustBuySell','投信買賣超股數']),dealer=pn(x,['DealerBuySell','自營商買賣超股數']),total=pn(x,['TotalBuySell','Total','三大法人買賣超股數']),derivedTotal=[foreign,trust,dealer].every(Number.isFinite)?foreign+trust+dealer:null;I.set(code,{code,foreign,trust,dealer,total,derivedTotal,date:tpIso(pv(x,['Date','日期']))||pv(x,['Date','日期']),provenance:'observed',derivedTotalProvenance:derivedTotal==null?'unavailable':'derived'})}for(const x of revs||[]){const code=String(pv(x,['公司代號','SecuritiesCompanyCode','Code'])||'').trim();if(!code)continue;R.set(code,{code,period:pv(x,['資料年月','年月']),mom:pn(x,['營業收入-上月比較增減(%)','上月比較增減(%)']),yoy:pn(x,['營業收入-去年同月增減(%)','去年同月增減(%)']),ytd:pn(x,['累計營業收入-前期比較增減(%)','前期比較增減(%)']),provenance:'observed'})}return{V,I,R}}
async function verifyTpex(code,r,snapshotRow){const hg=historyIntegrity(r,60),L=r.at(-1),x=snapshotRow||null,match=!!(x&&L&&Number.isFinite(x.c)&&Math.abs(Number(x.c)-Number(L.c))<.001),fresh=!!(L?.iso&&old(L.iso)<=4),dateMatch=!!(x&&L&&x.date===L.iso);return{fresh,match:match&&dateMatch,history:hg,complete:fresh&&match&&dateMatch&&hg.ok,date:L?.iso||null,text:x&&L?`${fmt(L.c)} / ${fmt(x.c)}｜${x.date}｜${hg.reason}`:'找不到代號',provenance:'observed_cross_check'}}
window.StockLabTPEx={tpexHealth,requireTpexHealth,tpexSnapshot,tpexExtras,verifyTpex};
