// TPEx official-data adapter. Core analysis remains deterministic and does not require GPT.
const TP='https://www.tpex.org.tw',TPA=`${TP}/openapi/v1`;
const TPU={snap:`${TPA}/tpex_mainboard_daily_close_quotes`,val:`${TPA}/tpex_mainboard_peratio_analysis`,inst:`${TPA}/tpex_3insti_daily_trading`,rev:`${TPA}/mopsfin_t187ap05_O`,hist:`${TP}/www/zh-tw/afterTrading/tradingStock`};
let TPHEALTH=null;
function tpHost(u){const h=new URL(u).hostname;if(h!=='www.tpex.org.tw')throw Error('非核准 TPEx 官方來源');return h}
async function tpexHealth(force=false){if(TPHEALTH&&!force)return TPHEALTH;try{const r=await fetch('./tpex-health.json',{cache:'no-store'});if(!r.ok)throw Error('健康快照讀取失敗');const x=await r.json();const age=x.generated_at?Math.floor((Date.now()-new Date(x.generated_at).getTime())/864e5):999;TPHEALTH={...x,fresh:age<=4,usable:x.schema_version===1&&x.source==='TPEx'&&x.verified===true&&x.status==='ok'&&age<=4};}catch(e){TPHEALTH={verified:false,usable:false,status:'failed',error:String(e.message||e)}}return TPHEALTH}
async function requireTpexHealth(){const h=await tpexHealth();if(!h.usable)throw Error(`TPEx 官方資料健康驗證未通過：${h.status||'unknown'}${h.error?'｜'+h.error:''}`);return h}
async function tpGet(u){await requireTpexHealth();tpHost(u);const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(`TPEx 官方資料連線失敗 ${r.status}`);return r.json()}
function pv(o,keys){for(const k of keys){if(o&&o[k]!=null&&String(o[k]).trim()!=='')return o[k]}return null}
function pn(o,keys){const v=pv(o,keys);return v==null?null:n(v)}
function tpIso(v){const s=String(v||'').replace(/\D/g,'');if(/^\d{7}$/.test(s))return `${+s.slice(0,3)+1911}-${s.slice(3,5)}-${s.slice(5,7)}`;if(/^\d{8}$/.test(s))return `${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`;const m=String(v||'').match(/(\d{2,3})\/(\d{2})\/(\d{2})/);return m?`${+m[1]+1911}-${m[2]}-${m[3]}`:null}
function tpMonthList(c){let d=new Date(),a=[];for(let i=0;i<c;i++){let x=new Date(d.getFullYear(),d.getMonth()-i,1);a.push(`${x.getFullYear()}/${String(x.getMonth()+1).padStart(2,'0')}/01`)}return a}
function findTable(x){if(!x||typeof x!=='object')return null;if(Array.isArray(x)){for(const v of x){const z=findTable(v);if(z)return z}return null}const f=x.fields||x.Fields||x.field||x.headers,d=x.data||x.Data||x.rows;if(Array.isArray(f)&&Array.isArray(d)){const s=f.join('|');if(/日期/.test(s)&&/(收盤|收盤價)/.test(s)&&/(開盤|開盤價)/.test(s))return{fields:f,data:d}}for(const v of Object.values(x)){const z=findTable(v);if(z)return z}return null}
function parseTpHist(j){const t=findTable(j);if(!t)return[];const ix=(...names)=>t.fields.findIndex(f=>names.some(k=>String(f).includes(k)));const di=ix('日期'),vi=ix('成交股數','成交仟股','成交量'),oi=ix('開盤'),hi=ix('最高'),li=ix('最低'),ci=ix('收盤');if([di,oi,hi,li,ci].some(i=>i<0))return[];return t.data.map(r=>({d:String(r[di]),iso:tpIso(r[di]),v:vi>=0?n(r[vi]):null,o:n(r[oi]),h:n(r[hi]),l:n(r[li]),c:n(r[ci])})).filter(x=>x.iso&&Number.isFinite(x.c)&&Number.isFinite(x.o)&&Number.isFinite(x.h)&&Number.isFinite(x.l)&&x.c>0&&x.o>0&&x.h>0&&x.l>0)}
async function tpexHist(code,c=6){await requireTpexHealth();const chunks=await Promise.all(tpMonthList(c).map(async d=>{try{tpHost(TPU.hist);const r=await fetch(`${TPU.hist}?code=${encodeURIComponent(code)}&date=${encodeURIComponent(d)}&id=&response=json`,{cache:'no-store'});if(!r.ok)return[];return parseTpHist(await r.json())}catch{return[]}}));const m=new Map();chunks.flat().forEach(x=>m.set(x.iso,x));return[...m.values()].sort((a,b)=>a.iso.localeCompare(b.iso))}
async function tpexSnapshot(){const rows=await tpGet(TPU.snap);if(!Array.isArray(rows))throw Error('TPEx 行情格式異常');return rows.map(x=>({market:'TPEx',code:String(pv(x,['SecuritiesCompanyCode','Code','證券代號','代號'])||'').trim(),name:String(pv(x,['CompanyName','SecuritiesCompanyName','Name','證券名稱','名稱'])||'').trim(),c:pn(x,['Close','ClosingPrice','收盤價','收盤']),v:pn(x,['TransactionAmount','TradeValue','TradingAmount','成交金額']),date:tpIso(pv(x,['Date','日期'])),provenance:'observed'})).filter(x=>/^\d{4}$/.test(x.code)&&x.c&&x.v&&x.date)}
async function tpexExtras(){const [vals,insts,revs]=await Promise.all([tpGet(TPU.val),tpGet(TPU.inst),tpGet(TPU.rev)]),V=new Map(),I=new Map(),R=new Map();for(const x of vals||[]){const code=String(pv(x,['SecuritiesCompanyCode','Code','證券代號','公司代號'])||'').trim();if(!code)continue;V.set(code,{code,pe:pn(x,['PriceEarningRatio','PERatio','本益比']),pb:pn(x,['PriceBookRatio','PBRatio','股價淨值比']),yield:pn(x,['YieldRatio','DividendYield','殖利率']),date:tpIso(pv(x,['Date','日期']))||pv(x,['Date','日期']),provenance:'observed'});}for(const x of insts||[]){const code=String(pv(x,['SecuritiesCompanyCode','Code','證券代號','公司代號'])||'').trim();if(!code)continue;const foreign=pn(x,['ForeignAndMainlandInvestorsBuySell','ForeignInvestorsBuySell','外資及陸資買賣超股數','外陸資買賣超股數']);const trust=pn(x,['InvestmentTrustBuySell','投信買賣超股數']);const dealer=pn(x,['DealerBuySell','自營商買賣超股數']);const total=pn(x,['TotalBuySell','Total','三大法人買賣超股數']);const derivedTotal=[foreign,trust,dealer].every(Number.isFinite)?foreign+trust+dealer:null;I.set(code,{code,foreign,trust,dealer,total,derivedTotal,date:tpIso(pv(x,['Date','日期']))||pv(x,['Date','日期']),provenance:'observed',derivedTotalProvenance:derivedTotal==null?'unavailable':'derived'});}for(const x of revs||[]){const code=String(pv(x,['公司代號','SecuritiesCompanyCode','Code'])||'').trim();if(!code)continue;R.set(code,{code,period:pv(x,['資料年月','年月']),mom:pn(x,['營業收入-上月比較增減(%)','上月比較增減(%)']),yoy:pn(x,['營業收入-去年同月增減(%)','去年同月增減(%)']),ytd:pn(x,['累計營業收入-前期比較增減(%)','前期比較增減(%)']),provenance:'observed'});}if(typeof loadQuarterly==='function')await loadQuarterly();return{V,I,R}}
async function verifyTpex(code,r,snapshotRow){const L=r.at(-1),x=snapshotRow||null,match=!!(x&&L&&Math.abs(x.c-L.c)<.001),fresh=!!(L&&old(L.iso)<=4),dateMatch=!!(x&&L&&x.date===L.iso),hg=typeof historyIntegrity==='function'?historyIntegrity(r,'day'):{ok:false,reason:'歷史完整性檢查不可用'};return{fresh,match:match&&dateMatch,history:hg,complete:fresh&&match&&dateMatch&&hg.ok,date:L?.iso||null,text:x&&L?`${fmt(L.c)} / ${fmt(x.c)}｜${x.date}｜${hg.reason}`:'找不到代號'}}
window.StockLabTPEx={tpexHealth,requireTpexHealth,tpexHist,tpexSnapshot,tpexExtras,verifyTpex};
